app.py
import os
from flask import Flask
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

def create_app():
    app = Flask(__name__)
    client = MongoClient(os.environ.get("MONGODB_URI"))
    app.db = client.get_default_database()

    app.register_blueprint(pages)
    return app

routes.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
import datetime
import uuid
from bson.objectid import ObjectId
from markupsafe import Markup

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")

# function to get the date for 3 days before and 3 days after a given date
# use a context processor so that all templates will have access to the date_range variable
@pages.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        # creates a list of dates from 3 days prior up to 3 days after start date
        dates = [start + datetime.timedelta(days=diff) for diff in range(-3, 4)]
        return dates
    return {"date_range": date_range}


def today_at_midnight():
    today = datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day) #by default time is at 0

@pages.route("/")
def index():
    date_str = request.args.get("date")
    # if user clicked on a date the page gets refreshed and selected_date gets set to that date
    if date_str:
        selected_date = datetime.datetime.fromisoformat(date_str)
    # if the user hasn't clicked on a date then selected_date should be set to today
    else:
        selected_date = today_at_midnight()
    #get all habits that were added on a date less than or equal to current date
    habits_on_date = current_app.db.habits.find({"added": {"$lte": selected_date}})
    completions = [
        habit["habit"]
        for habit in current_app.db.completions.find({"date": selected_date})
    ]

    return render_template(
        "index.html", 
        habits=habits_on_date, 
        completions=completions,
        title="Habit Tracker - Home", 
        selected_date=selected_date
        )


@pages.route("/add", methods=["GET", "POST"])
def add_habit():
    today = today_at_midnight()
    if request.form:
        current_app.db.habits.insert_one(
            {"_id": uuid.uuid4().hex, "added": today, "name": request.form.get("habit")}
        )
    return render_template(
        "add_habit.html", 
        title="Habit Tracker - Add Habit", 
        # selected_date should always be today so that we can only add habits starting from today
        selected_date=today)


#this method will get called whenever someone clicks on an incomplete habit
# and it will add the habit to the completions dictionary
@pages.route("/complete", methods=["POST"])
def complete():
    # get the values for 'date' and 'habitName' from the form
    date_string = request.form.get("date")
    habit = request.form.get("habitId")
    date = datetime.datetime.fromisoformat(date_string)
    #in the completions dictionary at the date element add the habit to the list
    current_app.db.completions.insert_one({"date": date, "habit": habit})
    # use redirect to call call the main page function to refresh the page with the updated changes
    return redirect(url_for(".index", date=date_string))

@pages.route("/incomplete", methods=["GET", "POST"])
def incomplete():
    # get the values for 'date' and 'habitName' from the form
    date_string = request.form.get("date")
    habit = request.form.get("habitId")
    date = datetime.datetime.fromisoformat(date_string)
    #in the completions dictionary at the date element remove the habit to the list
    current_app.db.completions.delete_one({"date": date, "habit": habit})
    # use redirect to call call the main page function to refresh the page with the updated changes
    return redirect(url_for(".index", date=date_string))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}

    <form class="form" method="POST">
        <textarea class="form__input" id="habit" name="habit" rows="3" placeholder="Add a new daily habit"></textarea>
        <button class="form__button" type="submit">Add</button>
    </form>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="habit-list">
    {% for habit in habits %}
        {% set completed = habit["_id"] in completions %}
        <!--if the habit is completed then display the habit with a completed icon-->
        {% if completed %}
            <div class="habit completed">
                <form class="habit__form" method="POST" action="{{ url_for('habits.incomplete') }}">
                    <!--when clicked the form sets variable habitName = habit
                        and sets date = selected_date when calling the complete method-->
                    <input type="hidden" name="habitId" value="{{ habit['_id'] }}">
                    <input type="hidden" name="date" value="{{ selected_date }}">
                    <button type="submit" class="habit__button">
                        {{ habit["name"] }}
                    </button>
                </form>
                <svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
            </div>
        <!--if the habit is not completed the habit should be displayed in a form 
            that when clicked calls on the 'complete' method to mark it as complete-->
        {% else %}
            <div class="habit">
                <form class="habit__form" method="POST" action="{{ url_for('habits.complete') }}">
                    <!--when clicked the form sets variable habitName = habit
                        and sets date = selected_date when calling the complete method-->
                    <input type="hidden" name="habitId" value="{{ habit['_id'] }}">
                    <input type="hidden" name="date" value="{{ selected_date }}">
                    <button type="submit" class="habit__button">
                        {{ habit['name'] }}
                    </button>
                </form>
            </div>
        {% endif %}
    {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title }}</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>
    
    <body>
        <header class="header">
            <h1 class="header__logo"><a href="{{ url_for('habits.index') }}" class="header__link">Habits</a></h1>
            {% if "add" not in request.endpoint %}
                <a href="{{ url_for('habits.add_habit') }}" class="header__link">+ Add new</a>
            {% endif %}
        </header>

        <main class="main">
            <section class="dates">
                <!--call our date_range function using 
                    the selected date that was passed into the render template
                    in order to get a list of dates and then display them-->
                {% for date in date_range(selected_date) %}
                    <!--dates are displayed with a link that when clicked on refreshes the page
                        and changes the 'date' variable-->
                    <!--the class of the date link is changed when the loop is at index 3
                        so that we can modify that specific date to look different-->
                    <a 
                        class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else ''}}" 
                        href="{{ url_for('habits.index', date=date)}}">
                        <time class="date" datetime="{{ date }}">
                            <!--display day of the week-->
                            <span>{{ date.strftime("%a") }}</span>
                            <!--display day of the month-->
                            <span>{{ date.strftime("%d") }}</span>
                        </time>
                    </a>
                {% endfor %}
            </section>
            {% block main_content %}
            {% endblock %}
        </main>
    </body>
</html>